name: Docs

on:
  push:
    paths:
      - docs

jobs:
  docs:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Docs
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}"
          https://api.github.com/repos/koishijs/koishijs.github.io/actions/workflows/deploy.yml/dispatches
